# Generated by Django 4.2.27 on 2025-12-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_customuser_full_name_customuser_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='manager_pin',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='رمز المدير'),
        ),
    ]
