# Generated by Django 6.0 on 2025-12-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
