# Generated by Django 6.0 on 2025-12-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_ticket_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ref',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
